### ISSUE TITLE
Bug/Question: No "number" before References section in HTML?

### ISSUE THREAD

**Issue by queirozfcom** [pandoc-ext/section-bibliographies#11]
Hi. I managed to generate the per-chapter references but the header will not follow the proper numbering. In the example below, it should be numbered as **2.8**

![xx](https://github.com/pandoc-ext/section-bibliographies/assets/1554354/ce302aa0-5a91-4f9a-a514-7bf3dcc6d76a)

Here is the relevant part of the config file:

```yaml
project:
  type: book

book:
  title: "my book title"
  author: "Felipe Almeida"
  date: "5/13/2023"
  chapters:
    - index.qmd

    - chapters/ch_01.qmd
    
    - part: parts/part_01.qmd
      chapters:
        - chapters/ch_02.qmd


filters:
  - section-bibliographies
bibliography: references.bib
reference-section-title: References

format:
  html:
    toc: true
    toc-expand: 1
    toc-depth: 4
  pdf:
    documentclass: scrreprt

crossref:
  chapters: true
```
