### ISSUE TITLE
quarto book, no references appear in the references sections

### ISSUE THREAD

**Issue by jpatteet** [pandoc-ext/section-bibliographies#13]
Hi,

I am trying to have multiple references sections in my PhD thesis.
One at the end of the "Manuscrit" part and one at the end of each Article (so three)

Unfortunately when I render in pdf, I have the reference title that appears but no references inside.

Here is my _quarto.yml file

```
project:
  type: book

book:
  title: "Book_PhD"
  author: "Name"
  date: "15.06.2023"

  chapters:
    - index.qmd
    - part: "Manuscrit (français)"
      chapters: 
        - Manuscrit/Intro.qmd
        - Manuscrit/Part1_Revue.qmd
        - Manuscrit/Part2_Terminologie.qmd
        - Manuscrit/Part3_Methodo.qmd
        - Manuscrit/Part4_Conclusion.qmd
        - Manuscrit/references.qmd
    - part: "Articles (english)"
      chapters:
        - Articles/Article1.qmd
        - Articles/Article2.qmd
        - Articles/Article_Methodology.qmd

filters: 
  - section-bibliographies
bibliography: Biblio.bib
reference-section-title: References
citeproc: false

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{multirow} 
        \usepackage{hyperref} 
        \usepackage[capitalise,noabbrev]{cleveref} 
  
editor: visual
```

Any idea of what I could try to make the references appear ?

**Comment by queirozfcom** [comment]
in my experience, setting `citeproc: false` didn't help at all

**Comment by ronnyhdez** [comment]
Hi!

I just created a minimum example in this repo: https://github.com/ronnyhdez/quarto_references_per_chapter

I'm using a Lua filter that I copied and pasted from the link provided in the readme.

This approach allowed me to generate references for each chapter in my thesis document successfully. However, I encountered an issue where the complete set of references is placed at the very end of the document, which posed a problem for me that I couldn't resolve. (I needed the complete references before my appendices section)

**Comment by tarleb** [comment]
Sorry for the late reply. I found that the following setting seems to work well with Quarto.

``` yaml
# Use this instead of "bibliography"
section-bibliographies:
  bibliography: references.bib
```

If there are issues remaining, please open a new issue, ideally with a reproducible example.
