### ISSUE TITLE
lang argument in quarto chapter yaml header is not taken into account

### ISSUE THREAD

**Issue by lucasvoirin** [pandoc-ext/section-bibliographies#15]
It seems that the lang argument in quarto chapter _metadata.yml or yaml header is not taken into account for pdf output. Only the lang argument in _quarto.yml is taken into account.

Here are the files used to reproduce this bug :

_quarto.qmd
---

```
project:
  type: book
  
lang: fr

book:
  chapters:
    - index.qmd
    - fr.qmd
    - en.qmd

bibliography: references.bib

filters:
  - section-bibliographies

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    citeproc: false

editor: visual
```

index.qmd
---

```
# Preface {.unnumbered}
```

en.qmd
---

```
---
lang: en
---

# English

[@ethier2020]
```

fr.qmd
---

```
---
lang: fr
---

# French

[@ethier2020]
```
references.bib
---

```
@article{ethier2020,
	title = {Using microphone arrays to investigate microhabitat selection by declining breeding birds},
	author = {Ethier, Jeffrey P. and Wilson, David R.},
	year = {2020},
	month = {07},
	date = {2020-07-01},
	journal = {Ibis},
	pages = {873--884},
	volume = {162},
	number = {3},
	doi = {10.1111/ibi.12785},
	note = {DOI: 10.1111/ibi.12785
MAG ID: 2977097847}
}
```
The outputs of these files running `quarto render index.qmd` are a html website with correct citation, i.e. "and" between authors names for english chapter and "et" between authors names for french chapter, and a pdf file with only french formated citations (as `lang: fr` is specified in `_quarto.yml`).
