### ISSUE TITLE
quarto book, references appear in first chapter only when html is rendered

### ISSUE THREAD

**Issue by SereDef** [pandoc-ext/section-bibliographies#20]
I am trying to have multiple references sections in my PhD thesis. This works fine in the rendered PDF (as shown in this example https://github.com/ronnyhdez/quarto_references_per_chapter) 

Unfortunately, I cannot get it to work in the HTML output. Here is a snippet of the _quarto.yml file (my latest attempt)

```
format:
  html:
    filters:
      - section-bibliographies.lua
  pdf:
    documentclass: scrreprt
    filters:
      - section-bibliographies.lua
```

This however only displays the whole reference list under the first chapter, and nothing in the following chapters.

Could you help me getting the same result in html (and docx too ideally)?

**Comment by tarleb** [comment]
This is surprising, it should work in HTML, too. Is this still an issue, or did you find a way?

And thank you for your patience. It took a while, but now there's time to work on this.

**Comment by aspatzier** [comment]
I have the same problem - the complete bibliography is rendering at the end of the first top level section...

**Comment by tarleb** [comment]
Things you could try:

- Changing the level, at which the bibliography is inserted
 
  ``` yaml
  metadata:
    section-bibliography:
      level: 2
  ```

- Modify the order, in which Quarto and this filter run. E.g.
  ``` yaml
  filters:
    - section-bibliographies
    - quarto
  ```

Should none of this work, then please provide a minimal example that could be used for debugging.
